project_id = "jdczbaswcxwemksfkiuf"

[functions.get-users]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.update-user-profile]
verify_jwt = true

[functions.submit-contact]
verify_jwt = false

[functions.submit-contact-message]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false

[functions.send-student-course-assignment]
verify_jwt = false

[functions.send-transactional-email]
verify_jwt = false

[functions.process-email-campaigns]
verify_jwt = true